### ISSUE TITLE
DQS issue. The dual quaternions are going the wrong way

### ISSUE THREAD

**Issue by mauriziokovacic** [AGGA-IRIT/Radium-Engine#118]
As you can see from the screenshot, something is going completely wrong

![jeff](https://cloud.githubusercontent.com/assets/13199218/18458252/7a32fdbc-7914-11e6-92f5-4569110c38b2.png)

**Comment by louen** [comment]
Can you give a repro case ? I loaded jeff and this worked perfectly to me.

**Comment by louen** [comment]
![screenshot_20160913_160450](https://cloud.githubusercontent.com/assets/1011507/18476861/f14e8486-79cb-11e6-9ede-7b16653012f6.png)

**Comment by mauriziokovacic** [comment]
I just clone master, without making any change. When playing Jeff animation it will do that.
It seems the same problem Baptiste was experiencing with his previous machine. Maybe it is something related to the OS or the machine.
I'm running under Ubuntu now, but on Botero there was Debian. Also Val didn't experience it and he was not using Ubuntu as well

**Comment by louen** [comment]
Ok you are right about the DQS actually.
![screenshot_20160913_175908](https://cloud.githubusercontent.com/assets/1011507/18481240/ceb617a8-79db-11e6-94a7-2444ac7817bb.png)

**Comment by mauriziokovacic** [comment]
I know. I'm just bad at things, not stupid :P

**Comment by louen** [comment]
So, the problem was that in some cases our strategy to resolve the quaternion antipodality ( in setFromTransform() ) was not correct.

I implemented the "naive" version which uses the strategy from the paper (Kavan &al. 2008) and it worked better.

I left the naive implementation as a reference and fixed our current "optimized" version.
