### ISSUE TITLE
Do we really need GLEW ?

### ISSUE THREAD

**Issue by MathiasPaulin** [AGGA-IRIT/Radium-Engine#131]
By making Viewer inherit from QOpenGLFunctions_4_1_Core we bring all the OpenGL 4.1 core functions to the namespace Viewer::
This might be a clean cross platform replacement for GLEW that is only needed on windows and can generate inclusion headache when combining with Qt ...
Actually, Viewer inherit from QOpenGLFunctions that bring OpenGLES 2.0 functions . why ?

**Comment by Zouch** [comment]
Using QOpenGLFunctions instead of QOpenGLFunctions_x_y was an error (I
think I was mislead by the qt code samples), I'll fix this.

For GLEW I do not really know if we really need it or not, but I remember
having problems getting opengl working on windows without it.
I can't remember if the problem was getting the function definitions or
linking against them though. I'll give it a try.

**Comment by Zouch** [comment]
Using `QOpenGLFunctions` instead of `QOpenGLFunctions_x_y` was an error (I
think I was mislead by the qt code samples), I'll fix this.

For GLEW I do not really know if we really need it or not, but I remember
having problems getting OpenGL working on windows without it.
I can't remember if the problem was getting the function definitions or
linking against them though. I'll give it a try.

**Comment by louen** [comment]
Undid merge (pull request) because compilation failed.

**Comment by nmellado** [comment]
Fixed by 62e1712fb1d633f6ab14b953c89e0c6b6b6ecc95. Closing
